/**
 * Default UI labels for the application.
 *
 * Used as fallback by the labelsController and as the base dataset for seeding.
 */

const DEFAULT_LABELS = {
  "common": {
    "appName": "School App",
    "welcome": "Welcome",
    "welcomeBack": "Welcome Back",
    "signIn": "Sign In",
    "logIn": "Log In",
    "logOut": "Log Out",
    "viewAsGuest": "View as Guest",
    "or": "OR",
    "cancel": "Cancel",
    "save": "Save",
    "submit": "Submit",
    "delete": "Delete",
    "edit": "Edit",
    "close": "Close",
    "done": "Done",
    "back": "Back",
    "next": "Next",
    "tryAgain": "Try Again",
    "loading": "Loading...",
    "noData": "No Data",
    "search": "Search",
    "reject": "Reject",
    "approve": "Approve",
    "present": "Present",
    "absent": "Absent",
    "total": "Total",
    "viewAll": "View All",
    "filterByClass": "Filter by Class",
    "selectClass": "Select Class",
    "room": "Room",
    "date": "Date",
    "type": "Type",
    "name": "NAME",
    "yes": "Yes",
    "no": "No",
    "ok": "OK",
    "confirm": "Confirm",
    "pending": "Pending",
    "history": "History",
    "students": "students",
    "teaching": "Teaching",
    "somethingWentWrong": "Something went wrong",
    "noInternetConnection": "No internet connection",
    "youAreOffline": "You are currently offline",
    "class": "Class",
    "branch": "Branch",
    "gender": "Gender",
    "bloodGroup": "Blood Group",
    "dateOfBirth": "Date of Birth",
    "address": "Address",
    "designation": "Designation",
    "joiningDate": "Joining Date",
    "admissionDate": "Admission Date",
    "guardianName": "Guardian Name",
    "guardianPhone": "Guardian Phone",
    "altPhone": "Alt Phone",
    "regNo": "Reg No",
    "satsNo": "SATS No",
    "penNo": "PEN No",
    "apaarId": "APAAR ID",
    "reason": "Reason",
    "used": "Used",
    "remaining": "Remaining",
    "low": "LOW",
    "overview": "Overview",
    "unknown": "Unknown",
    "na": "N/A",
    "classTeacher": "Class Teacher",
    "headmaster": "Headmaster",
    "managementSuperAdmin": "Management (Super Admin)",
    "to": "To",
    "from": "From",
    "category": "Category",
    "subjectLabel": "Subject",
    "detailedDescriptionPlaceholder": "Detailed description...",
    "fillAllFields": "Please fill all fields",
    "studentsCount": "students",
    "classTeacherRole": "Class Teacher",
    "update": "Update",
    "general": "General",
    "studentRequired": "Student *",
    "classRequired": "Class *",
    "updating": "Updating...",
    "highest": "Highest",
    "all": "All",
    "inProgress": "In Progress",
    "resolved": "Resolved",
    "rejected": "Rejected",
    "notAssigned": "Not assigned",
    "searching": "Searching...",
    "retry": "Retry",
    "supportStaff": "Support Staff",
    "currentRole": "Current Role",
    "teacher": "Teacher",
    "by": "By"
  },
  "toasts": {
    "loggedInSuccessfully": "Logged in successfully",
    "loginFailed": "Login failed",
    "networkError": "Network error. Please try again.",
    "enterBothFields": "Please enter both phone number and password.",
    "passwordResetSuccessfully": "Password reset successfully",
    "failedToResetPassword": "Failed to reset password",
    "allFieldsMandatory": "All fields are mandatory",
    "passwordMinLength": "New password must be at least 8 characters long",
    "passwordsDoNotMatch": "Passwords do not match",
    "failedToUpdateSettings": "Failed to update settings",
    "notificationDeleted": "Notification deleted",
    "failedToDeleteNotification": "Failed to delete notification",
    "complaintRaised": "Complaint raised successfully",
    "failedToRaiseComplaint": "Failed to raise complaint",
    "pleaseFillAllFields": "Please fill all fields",
    "feedbackSent": "Feedback sent successfully",
    "failedToSendFeedback": "Failed to send feedback",
    "pleaseSelectClass": "Please select a class",
    "pleaseSelectStudent": "Please select a student",
    "pleaseEnterFeedback": "Please enter a feedback message",
    "selectClassFirst": "Please select a class first",
    "feedbackUpdated": "Feedback updated",
    "updateFailed": "Update failed",
    "feedbackDeleted": "Feedback deleted",
    "deleteFailed": "Delete failed",
    "messageCannotBeEmpty": "Message cannot be empty",
    "complaintUpdated": "Complaint updated",
    "failedToUpdateStatus": "Failed to update status",
    "leaveApplied": "Leave applied successfully",
    "failedToApplyLeave": "Failed to apply leave",
    "pleaseEnterReason": "Please enter a reason",
    "endDateBeforeStart": "End date cannot be before start date",
    "leaveUpdated": "Leave updated successfully",
    "errorUpdatingStatus": "Error updating status",
    "rejectionReasonRequired": "Rejection reason and comments are required",
    "examDateUpdated": "Exam date updated",
    "failedToUpdateDate": "Failed to update date",
    "examDeleted": "Exam deleted successfully",
    "failedToDeleteExam": "Failed to delete exam",
    "failedToInitExams": "Failed to initialize exams",
    "enterValidTotalMarks": "Please enter valid total marks",
    "selectAtLeastOneClass": "Please select at least one class",
    "subjectCreated": "Subject created",
    "subjectUpdated": "Subject updated",
    "failedToSaveSubject": "Failed to save",
    "subjectDeleted": "Subject deleted",
    "failedToDeleteSubject": "Failed to delete",
    "subjectNameRequired": "Subject name is required",
    "subjectsAssigned": "Successfully assigned subject(s)",
    "errorAssigningSubjects": "Error assigning subjects",
    "failedToRemoveTeacher": "Failed to remove teacher from subject",
    "selectAtLeastOneSubject": "Please select at least one subject",
    "notificationSent": "Notification sent successfully",
    "failedToSendNotification": "Failed to send notification",
    "enterTitleAndMessage": "Please enter title and message",
    "academicYearCreated": "Academic Year created",
    "failedToCreate": "Failed to create",
    "yearIncrementedPromoted": "Year Incremented & Students Promoted!",
    "failedToIncrementYear": "Failed to increment year",
    "nameFormatError": "Name must be in YYYY-YYYY format",
    "paymentRecorded": "Payment recorded successfully",
    "paymentFailed": "Payment failed",
    "feeStructureSaved": "Fee structure saved",
    "failedToSaveStructure": "Failed to save structure",
    "errorSearchingStudent": "Error searching student",
    "invalidAmount": "Invalid amount",
    "fillNameAndAmount": "Please fill name and amount",
    "selectClassAndYear": "Select class and academic year",
    "addAtLeastOneFee": "Add at least one fee component",
    "selectAtLeastOneStudent": "Select at least one student",
    "userCreated": "User created successfully",
    "failedToCreateUser": "Failed to create user",
    "userUpdated": "User updated successfully",
    "failedToUpdateUser": "Failed to update user",
    "userDeleted": "User deleted successfully",
    "failedToDeleteUser": "Failed to delete user",
    "promotionReverted": "Promotion reverted successfully",
    "failedToRevertPromotion": "Failed to revert promotion",
    "classCreated": "Class created",
    "failedToCreateClass": "Failed to create",
    "classUpdated": "Class updated",
    "failedToUpdateClass": "Failed to update",
    "classDeleted": "Class deleted",
    "failedToDeleteClass": "Failed to delete",
    "nameIsRequired": "Name is required",
    "importCompleted": "Import completed successfully",
    "syncFailed": "Sync failed",
    "failedToLoadContent": "Failed to load content",
    "errorLoadingData": "Error loading data"
  },
  "alerts": {
    "deleteNotificationTitle": "Delete Notification",
    "deleteNotificationMessage": "Are you sure you want to delete this notification? This action cannot be undone.",
    "deleteSubjectTitle": "Delete Subject",
    "deleteSubjectMessage": "Are you sure? This will remove the subject permanently.",
    "deleteClassTitle": "Delete Class",
    "deleteClassMessage": "Are you sure you want to delete this class?",
    "deleteExamTitle": "Delete Exam",
    "deleteExamMessage": "This exam and all its marks will be permanently deleted.",
    "deleteComplaintTitle": "Delete Complaint",
    "deleteComplaintMessage": "Are you sure you want to delete this complaint?",
    "incrementYearTitle": "Increment Academic Year",
    "incrementYearMessage": "This will create a new year and promote all students. Continue?"
  },
  "login": {
    "title": "Welcome Back",
    "subtitle": "Sign in to continue to School App",
    "phoneLabel": "Phone Number",
    "phonePlaceholder": "Enter phone number",
    "passwordLabel": "Password",
    "passwordPlaceholder": "Enter password",
    "signInButton": "Sign In",
    "viewAsGuestButton": "View as Guest"
  },
  "home": {
    "welcomeTo": "Welcome to",
    "aboutUs": "About Us",
    "branches": "Branches",
    "ourMission": "Our Mission",
    "branchMangasuli": "Renuka Nagar, Mangasuli",
    "branchMangasuliDesc": "Kindergarten to 10th Standard.",
    "branchUgarKhurd": "Meenatai Nagar, Ugar Khurd",
    "branchUgarKhurdDesc": "Kindergarten."
  },
  "nav": {
    "home": "Home",
    "class": "Class",
    "dashboard": "Dashboard",
    "admin": "Admin",
    "classes": "Classes",
    "attendance": "Attendance",
    "menu": "Menu"
  },
  "menu": {
    "title": "Menu",
    "subtitle": "Settings & More",
    "profile": "Profile",
    "profileSubtitle": "View & edit your profile",
    "events": "Events",
    "eventsSubtitle": "School calendar & upcoming",
    "complaints": "Complaints",
    "complaintsSubtitle": "Raise issues or feedback",
    "preferences": "Preferences",
    "darkMode": "Dark Mode",
    "darkModeOnSubtitle": "Easy on the eyes",
    "darkModeOffSubtitle": "Bright and clear",
    "followUs": "Follow Us",
    "youtube": "YouTube",
    "instagram": "Instagram",
    "location": "Location"
  },
  "profile": {
    "title": "Profile",
    "loadingProfile": "Loading profile...",
    "guestUser": "Guest User",
    "loginToAccess": "Login to access all features",
    "resetPassword": "Reset Password",
    "contactInfo": "CONTACT INFO",
    "studentDetails": "STUDENT DETAILS",
    "staffDetails": "STAFF DETAILS",
    "personalDetails": "PERSONAL DETAILS",
    "academicIds": "ACADEMIC IDs",
    "currentPasswordLabel": "CURRENT PASSWORD",
    "currentPasswordPlaceholder": "Enter current password",
    "newPasswordLabel": "NEW PASSWORD",
    "newPasswordPlaceholder": "At least 8 characters",
    "confirmPasswordLabel": "CONFIRM NEW PASSWORD",
    "confirmPasswordPlaceholder": "Re-enter new password",
    "supportStaff": "Support Staff"
  },
  "notifications": {
    "title": "Notifications",
    "allCaughtUp": "All caught up!",
    "noNotificationsMessage": "No notifications to show at the moment.",
    "settingsTitle": "Notifications",
    "settingsSubtitle": "Choose what you would like to be notified about.",
    "alertsSuffix": "Alerts",
    "notification": "Notification"
  },
  "requests": {
    "title": "Attendance",
    "subtitle": "Manage attendance and requests",
    "myAttendance": "My Attendance",
    "myAttendanceSubtitle": "View your attendance history",
    "markAttendance": "Mark Attendance",
    "markAttendanceAdminSubtitle": "Mark staff and student attendance",
    "markAttendanceTeacherSubtitle": "Mark student attendance",
    "leaveRequests": "Leave Requests",
    "leaveRequestsStudentSubtitle": "Apply for leave and track status",
    "leaveRequestsAdminSubtitle": "Approve or reject leave requests"
  },
  "historyScreen": {
    "title": "History",
    "pastExams": "Past exams",
    "reports": "Reports",
    "noPastExams": "No past exams found",
    "examHistoryInfo": "Exam history is available in the Reports section of Academic Year or per class in Exam Schedule.",
    "goToAcademicYear": "Go to Academic Year"
  },
  "events": {
    "title": "Events",
    "subtitle": "Calendar & events",
    "noEventsTitle": "No Events",
    "noEventsMessage": "No events on this date.",
    "addEvent": "Add Event",
    "editEvent": "Edit Event",
    "deleteEvent": "Delete Event"
  },
  "subjects": {
    "title": "Manage Subjects",
    "subtitle": "Master List",
    "searchPlaceholder": "Search subjects...",
    "noSubjectsFound": "No subjects found",
    "namePlaceholder": "e.g. Mathematics",
    "codePlaceholder": "e.g. MATH101",
    "usageDetails": "Usage Details",
    "teachers": "TEACHERS",
    "noTeachersAssigned": "No teachers assigned"
  },
  "teacher": {
    "dashboardTitle": "My Teaching",
    "dashboardSubtitle": "Manage your classes and subjects",
    "staffDashboardSubtitle": "Staff quick actions",
    "schoolTimetable": "School Timetable",
    "viewAllSchedules": "View all classes and period schedules",
    "manageExams": "Manage Exams",
    "viewTimetable": "View Timetable",
    "classTeacher": "CLASS TEACHER",
    "myClass": "MY CLASS",
    "asClassTeacher": "As Class Teacher",
    "mySubjects": "My Subjects",
    "notClassTeacherTitle": "Not a Class Teacher",
    "notClassTeacherMessage": "You are not a class teacher of any class. Check \"My Subjects\" tab to see subjects you teach.",
    "noSubjectsTitle": "No Subjects Assigned",
    "noSubjectsMessage": "No subjects have been assigned to you yet. Check \"As Class Teacher\" tab to see your class.",
    "loadingDashboard": "Loading dashboard...",
    "examManagement": "Exam Management",
    "manageSchedules": "Manage Schedules",
    "noExamsForClass": "No exams found for this class",
    "roomPlaceholder": "e.g. Room 101",
    "totalMarksPlaceholder": "100",
    "passingMarksPlaceholder": "90",
    "instructionsPlaceholder": "Enter instructions...",
    "applyForLeave": "Apply for Leave",
    "leaveType": "LEAVE TYPE",
    "fullDay": "Full Day",
    "halfDay": "Half Day",
    "slot": "SLOT",
    "morning": "Morning",
    "afternoon": "Afternoon",
    "startDate": "START DATE",
    "endDate": "END DATE",
    "reasonLabel": "REASON",
    "reasonPlaceholder": "Enter reason for leave...",
    "submitApplication": "Submit Application",
    "leaveManagement": "Leave Management",
    "rejectionReason": "Rejection Reason",
    "approvalNote": "Approval Note",
    "editDecision": "Edit Decision",
    "rejectionDetails": "Rejection Details",
    "myAttendanceTitle": "My Attendance",
    "myAttendanceSubtitle": "Track your attendance record",
    "noClassesTitle": "No Classes",
    "loadingAttendance": "Loading attendance records...",
    "totalDays": "Total Days",
    "rejectionReasonPlaceholder": "e.g., Exam Period, Staff Shortage",
    "commentPlaceholder": "Add detailed comments...",
    "notePlaceholder": "Add a note...",
    "contentPostedSuccess": "Content posted successfully",
    "contentPostedFailure": "Failed to post content",
    "subjectDetails": "Subject Details",
    "teachersLabel": "Teachers",
    "classContent": "Class Content",
    "performance": "Performance",
    "noContentPostedYet": "No content posted yet.",
    "contentType_homework": "Homework",
    "contentType_news": "News",
    "contentType_notes": "Notes"
  },
  "student": {
    "myAttendanceTitle": "My Attendance",
    "myAttendanceSubtitle": "Track your attendance record",
    "retrievingAcademicHistory": "Retrieving your academic history...",
    "pastReports": "Past Reports",
    "academicJourney": "Your Academic Journey",
    "noHistoryFound": "No History Found",
    "noArchivedRecords": "Looks like you don't have any archived academic records yet.",
    "unknownYear": "Unknown Year",
    "finalStatus": "Final Status",
    "status_Passed": "Passed",
    "status_Failed": "Failed",
    "status_Promoted": "Promoted"
  },
  "feedback": {
    "feedback": "Feedback",
    "sentFeedback": "Sent Feedback",
    "logs": "Logs",
    "giveFeedback": "Give Feedback",
    "sentSuccess": "Feedback sent successfully",
    "sentFailure": "Failed to send feedback",
    "selectClassError": "Please select a class",
    "selectStudentError": "Please select a student",
    "enterFeedbackMessageError": "Please enter a feedback message",
    "selectClassFirstError": "Please select a class first",
    "selectClassPlaceholder": "Select Class",
    "selectStudentPlaceholder": "Select Student",
    "feedbackMessageRequired": "Feedback Message *",
    "feedbackPlaceholder": "Write your feedback here...",
    "sendFeedback": "Send Feedback",
    "selectClassTitle": "Select Class",
    "searchClassPlaceholder": "Search class...",
    "noClassesFound": "No classes found",
    "selectStudentTitle": "Select Student",
    "searchStudentPlaceholder": "Search student...",
    "noStudentsFound": "No students found",
    "updated": "Feedback updated",
    "updateFailed": "Update failed",
    "deleted": "Feedback deleted",
    "deleteFailed": "Delete failed",
    "deleteFeedbackTitle": "Delete Feedback",
    "deleteConfirmMessage": "Are you sure you want to delete this feedback?",
    "noFeedbackYet": "No Feedback Yet",
    "noFeedbackSent": "No Feedback Sent",
    "noFeedbackYetDesc": "Your teachers haven't given you any feedback yet.",
    "noFeedbackSentDesc": "You haven't given feedback to any students yet.",
    "editFeedback": "Edit Feedback",
    "generalFeedback": "General Feedback"
  },
  "reports": {
    "classReports": "Class Reports",
    "performanceAnalyticsInsights": "Performance analytics and insights",
    "filterByExamType": "Filter by Exam Type",
    "allExams": "All Exams",
    "loadingClassAnalytics": "Loading class analytics...",
    "selectClassToView": "Select a class to view reports",
    "avgScore": "Avg Score",
    "totalMarks": "Total Marks",
    "gradeDistributionTitle": "Grade Distribution",
    "gradeDistributionSubtitle": "Distribution across performance bands",
    "performanceTrendsTitle": "Performance Trends",
    "performanceTrendsSubtitle": "Exam-wise average progression",
    "topPerformersTitle": "Top Performers",
    "topPerformersSubtitle": "Top 5 students in the class",
    "studentRankingsTitle": "Student Rankings",
    "scored": "Scored",
    "marks": "Marks",
    "subjectsCount": "subjects",
    "subjectBreakdown": "Subject Breakdown"
  },
  "admin": {
    "title": "Admin Panel",
    "subtitle": "Manage your school",
    "teacherSubjectsTitle": "Teacher-Subject Assignments",
    "teacherSubjectsSubtitle": "Manage which teachers teach which subjects",
    "searchTeachersPlaceholder": "Search teachers...",
    "searchSubjectsPlaceholder": "Search subjects...",
    "performanceTitle": "School Performance",
    "performanceSubtitle": "Comprehensive analytics dashboard",
    "broadcastTitle": "Broadcast Announcement",
    "broadcastSubtitle": "Send alerts to users",
    "titleLabel": "Title",
    "titlePlaceholder": "e.g. School Closed Tomorrow",
    "messageLabel": "Message",
    "messagePlaceholder": "Type your message here...",
    "typeLabel": "Type",
    "targetAudience": "Target Audience",
    "selectClassLabel": "Select Class",
    "noClasses": "No Classes",
    "userCreatedSuccess": "User created successfully",
    "userCreatedFailure": "Failed to create user",
    "userUpdatedSuccess": "User updated successfully",
    "userUpdatedFailure": "Failed to update user",
    "userDeletedSuccess": "User deleted successfully",
    "userDeletedFailure": "Failed to delete user",
    "promotionRevertedSuccess": "Promotion reverted successfully",
    "promotionRevertedFailure": "Failed to revert promotion",
    "loadingUsers": "Loading users...",
    "failedToLoadProfile": "Failed to load user profile",
    "failedToLoadUsers": "Failed to load users",
    "noUsersFound": "No users found",
    "academicManagement": "Academic Management",
    "academicYear": "Academic Year",
    "subjects": "Subjects",
    "teachingManagement": "Teaching Management",
    "teacherSubjects": "Teacher Subjects",
    "classOperations": "Class Operations",
    "timetable": "Timetable",
    "exams": "Exams",
    "examAnalytics": "Exam Analytics",
    "financial": "Financial",
    "fees": "Fees",
    "communication": "Communication",
    "complaints": "Complaints",
    "broadcast": "Broadcast",
    "userManagement": "User Management",
    "addUser": "Add User",
    "searchUsersPlaceholder": "Search users...",
    "allRoles": "All Roles",
    "admin": "Admin",
    "manageUsersDesc": "Manage users and permissions"
  },
  "leaves": {
    "title": "Leave Management"
  },
  "fees": {
    "title": "Fee Management"
  },
  "timetable": {
    "title": "Timetable"
  },
  "exams": {
    "title": "Exams"
  },
  "complaints": {
    "title": "Complaints & Feedback",
    "raiseComplaint": "Raise Complaint",
    "giveFeedback": "Give Feedback",
    "complaints": "Complaints",
    "inbox": "Inbox",
    "inboxEmpty": "Inbox Empty",
    "noComplaintsRaised": "No Complaints Raised",
    "noComplaintsRaisedDesc": "You haven't raised any complaints. Tap the + button to raise one.",
    "inboxEmptyDesc": "No complaints have been received.",
    "updated": "Complaint updated",
    "updateStatusFailure": "Failed to update status",
    "adminResponseLabel": "ADMIN RESPONSE",
    "updateStatus": "Update Status",
    "complaintLabel": "Complaint:",
    "setStatusLabel": "Set Status",
    "adminResponseTitle": "Admin Response",
    "writeResponsePlaceholder": "Write a response to the user...",
    "updateComplaint": "Update Complaint"
  },
  "academicYear": {
    "title": "Academic Years",
    "createYear": "Create Year"
  },
  "dashboard": {
    "today": "Today",
    "thisWeek": "This Week",
    "thisMonth": "This Month",
    "last30Days": "Last 30 Days",
    "thisYear": "This Year",
    "lastYear": "Last Year",
    "allTime": "All Time",
    "loadingDashboard": "Loading dashboard...",
    "noDataTitle": "No Data",
    "noDataMessage": "Dashboard data is not available"
  },
  "search": {
    "placeholder": "Search students, exams, complaints...",
    "noResults": "No results found",
    "recentSearches": "Recent Searches",
    "tryDifferentKeywords": "Try different keywords",
    "categoryPeople": "People",
    "categoryClasses": "Classes",
    "categorySubjects": "Subjects",
    "categoryExams": "Exams",
    "categoryComplaints": "Complaints",
    "categoryEvents": "Events",
    "startTypingToSearch": "Start typing to search"
  },
  "states": {
    "loadingDefault": "Loading...",
    "errorDefault": "Something went wrong",
    "retryButton": "Try Again"
  },
  "header": {
    "welcomeTo": "Welcome to",
    "notifications": "Notifications",
    "goBack": "Go back"
  },
  "errorBoundary": {
    "title": "Oops! Something went wrong",
    "message": "An unexpected error occurred. Please try again.",
    "retryButton": "Retry"
  },
  "demo": {
    "bannerText": "Demo Mode"
  }
};

module.exports = DEFAULT_LABELS;
